# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'CPDF | Checkout GIT repository.'
  become: yes
  become_user: 'root'
  git:
    repo: 'https://github.com/coherentgraphics/cpdf-binaries.git'
    dest: '/usr/local/cpdf'
    update: '{{ cpdf_update }}'

- name: 'CPDF | Symlink executable binary.'
  become: yes
  file:
    path: '/usr/local/bin/cpdf'
    src: '/usr/local/cpdf/Linux-Intel-{{ "64" if ansible_architecture == "x86_64" else "32" }}bit/cpdf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'link'